Fix build

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -5,34 +5,28 @@ for DOCKERFILE_PATH in $(ls Dockerfile*); do
   # postcheckout
   BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)
 
-  [ "${BUILD_ARCH}" == "Dockerfile" ] && \
-      { echo 'qemu-user-static: Download not required for current arch'; exit 0; }
+  if [ "${BUILD_ARCH}" != "Dockerfile" ];then 
+    QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
+    QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
+    QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
+        | grep 'name.*v[0-9]' \
+        | head -n 1 \
+        | cut -d '"' -f 4)
 
-  QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
-  QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
-  QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
-      | grep 'name.*v[0-9]' \
-      | head -n 1 \
-      | cut -d '"' -f 4)
+    curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
+        | tar xzv
 
-  curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
-      | tar xzv
+    # prebuild
 
-  # prebuild
-  BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)
+    docker run --rm --privileged multiarch/qemu-user-static:register --reset
 
-  [ "${BUILD_ARCH}" == "Dockerfile" ] && \
-      { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }
-
-
-  docker run --rm --privileged multiarch/qemu-user-static:register --reset
+    QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
+  else
+    echo 'qemu-user-static: Download not required for current arch'
+  fi
+  
 
   # build
-  BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)
-
-  [ "${BUILD_ARCH}" != "Dockerfile" ] && \
-  QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
-
 
   docker build \
       --file "${DOCKERFILE_PATH}" \
@@ -50,5 +44,4 @@ for DOCKERFILE_PATH in $(ls Dockerfile*); do
       } 
   } || docker rm "test-${DOCKER_TAG}" || true
 
-  # post push
 done
